name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on:
  push:
    branches: [master]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Staring Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version}}
      - name: install client modules
        run: npm install
        working-directory: ./client

      - name: build client project
        run: npm run build
        working-directory: ./client

      - name: install server modules
        run: npm install
        working-directory: ./server

      - name: build server project
        run: npm run build
        working-directory: ./server
